x = int(input("Give me the first number: "))
y = int(input("GIve me the second number: "))
print("Thank you!")
print(x, "+", y, "=", x + y)
print(x, "-", y, "=", x - y)
print(x, "/", y, "=", x / y)
print(x, "*", y, "=", x * y)
